version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

gomod:
  proxy: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - binary: "MCST"
    main: "./cmd/MCST"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
      - freebsd
      - netbsd
      - illumos
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
      - ppc64le
      - s390x
      - mips64
      - mips64le
      - riscv64
      - loong64
    goarm:
      - "6"
      - "7"
    gomips:
      - hardfloat
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: freebsd
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/Arama0517/MCST/internal/build.version={{ .Version }}
      - -X github.com/Arama0517/MCST/internal/build.commit={{ .Commit }}
      - -X github.com/Arama0517/MCST/internal/build.date={{ .CommitDate }}
      - -X github.com/Arama0517/MCST/internal/build.builtBy=GoReleaser
      - -X github.com/Arama0517/MCST/internal/build.treeState={{ .IsGitDirty }}

archives:
  - format: tar.gz
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

release:
  name_template: "v{{ .Version }}"
  footer: |
    **Full Changelog**: https://github.com/Arama-Vanarana/MCServerTool/compare/{{ .PreviousTag }}...{{ if .IsNightly }}nightly{{ else }}{{ .Tag }}{{ end }}

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/Arama0517/MCServerTool
    description: A command-line utility making Minecraft server creation quick and easy for beginners.
    maintainer: Arama <arama0517@foxmail.com>
    license: GPL-v3
    vendor: MCST
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/MCST.bash
        dst: /usr/share/bash-completion/completions/MCST
        file_info:
          mode: 0644
      - src: ./completions/MCST.fish
        dst: /usr/share/fish/vendor_completions.d/MCST.fish
        file_info:
          mode: 0644
      - src: ./completions/MCST.zsh
        dst: /usr/share/zsh/site-functions/_MCST
        file_info:
          mode: 0644
      - src: ./manpages/MCST.1.gz
        dst: /usr/share/man/man1/MCST.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/MCST/copyright
        file_info:
          mode: 0644
    formats:
      - deb
      - rpm
      - archlinux
    dependencies:
      - aria2
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

brews:
  - name: MCST
    repository:
      owner: Arama0517
      name: homebrew-tab
    directory: Formula
    goarm: "7"
    homepage: https://github.com/Arama0517/MCServerTool
    description: A command-line utility making Minecraft server creation quick and easy for beginners.
    license: GPL-v3
    test: |
      system "#{bin}/MCST -v"
    dependencies:
      - name: aria2
    extra_install: |-
      bash_completion.install "completions/MCST.bash" => "MCST"
      zsh_completion.install "completions/MCST.zsh" => "_MCST"
      fish_completion.install "completions/MCST.fish"
      man1.install "manpages/MCST.1.gz"

scoops:
  - name: MCST
    repository:
      owner: Arama0517
      name: scoop-bucket
    directory: bucket
    homepage: https://github.com/Arama0517/MCServerTool
    description: A command-line utility making Minecraft server creation quick and easy for beginners.
    depends:
      - aria2
    license: GPL-v3