version: 3

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org,direct

tasks:
  setup:
    desc: 下载依赖
    cmds:
      - go mod tidy

  run:
    desc: 构建
    cmds:
      - go run . {{.CLI_ARGS}}

  build:
    desc: 构建
    sources:
      - ./**/*.go
    generates:
      - ./MCST
    cmds:
      - go build -o MCST

  test:
    desc: 测试
    cmds:
      - go test -failfast -race -parallel 2 -timeout=5m ./...

  lint:
    desc: 使用golangci-lint检查代码
    cmds:
      - golangci-lint run --config ./.golangci.yaml {{.CLI_ARGS}} ./...

  ci:
    desc: 运行所有CI步骤
    cmds:
      - task: setup
      - task: build
      - task: test

  default:
    desc: 运行默认任务
    cmds:
      - task: run

  release:
    desc: 创建一个新Tag
    vars:
      NEXT:
        sh: svu n
    cmds:
      - git tag {{.NEXT}}
      - echo {{.NEXT}}
      - git push origin --tags

  test:goreleaer:
    desc: 测试发布
    cmds:
      - goreleaser release --skip publish --snapshot --clean

  test:goreleaser:clean:
    desc: 删除测试发布所产生的文件/文件夹
    cmds:
      - rm ./dist ./completions ./manpages -rf