version: 3

tasks:
  setup:
    desc: 下载依赖
    cmds:
      - go mod tidy

  run:
    desc: 构建
    cmds:
      - go run ./cmd/MCST {{ .CLI_ARGS }}

  build:
    desc: 构建
    sources:
      - ./**/*.go
    generates:
      - ./MCST
    cmds:
      - go build -o MCST ./cmd/MCST

  test:
    desc: 测试
    env:
      LC_ALL: C
    vars:
      SOURCE_FILES: '{{default "./..." .SOURCE_FILES}}'
      TEST_PATTERN: '{{default "." .TEST_PATTERN}}'
    cmds:
      - go test {{ .CLI_ARGS }} -failfast {{ .SOURCE_FILES }} -run {{ .TEST_PATTERN }} -timeout=5m

  test:goreleaer:
    desc: 测试发布
    cmds:
      - goreleaser release --skip publish --snapshot --clean

  test:goreleaser:clean:
    desc: 删除测试发布所产生的文件/文件夹
    cmds:
      - rm ./dist ./completions ./manpages -rf

  lint:
    desc: 使用golangci-lint检查代码
    cmds:
      - golangci-lint run --config ./.golangci.yaml {{.CLI_ARGS}} ./...

  fmt:
    desc: 使用 gofumpt 格式化全部代码
    cmds:
      - gofumpt -w -l .

  ci:
    desc: 运行所有CI步骤
    cmds:
      - task: setup
      - task: build
      - task: test

  default:
    desc: 运行默认任务
    cmds:
      - task: run

  release:
    desc: 创建一个新Tag
    vars:
      NEXT:
        sh: svu n
    cmds:
      - git tag {{.NEXT}}
      - echo {{.NEXT}}
      - git push origin --tags