name: CI

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
jobs:
    CI:
        runs-on: ubuntu-latest]
        steps:
            - uses: actions/checkout@v4
            - name: 设置 Go 版本
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22.3"
            - name: 构建
              run: go build -v ${{ github.workspace }}/main.go
            - name: 测试
              run: go test -v ${{ github.workspace }}/...