name: CI

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

permissions:
    # Required: allow read access to the content for analysis.
    contents: read
    # Optional: allow read access to pull request. Use with `only-new-issues` option.
    pull-requests: read
    # Optional: allow write access to checks to allow the action to annotate code in the PR.
    checks: write

jobs:
    check:
        strategy:
            matrix:
                go: [stable]
                os: [ubuntu-latest, windows-latest]
        name: lint
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: 初始化 Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
            - name: 检查代码质量
              uses: golangci/golangci-lint-action@v6
              with:
                  version: latest
                  args: --verbose
            - name: 测试
              run: go test -v ./...
