name: CI

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
jobs:
    windows:
        name: 检查代码存在问题
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: 构建
              run: go build -v ${{ github.workspace }}\cmd\MCSCS\main.go
            - name: 测试
              run: go test -short -race -v ${{ github.workspace }}\pkg\...
    linux:
        name: 检查代码存在问题
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: 构建
              run: go build -v ${{ github.workspace }}/cmd/MCSCS/main.go
            - name: 测试
              run: go test -short -race -run '^(?!TestDetectJava$)' -v ${{ github.workspace }}/pkg/...
