name: lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - ".github/workflows/*.yml"

env:
  GOPROXY: "https://proxy.golang.org"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - run: task ci