name: golangci-lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    GOPROXY: "https://proxy.golang.org"

permissions:
    # Required: allow read access to the content for analysis.
    contents: read

jobs:
    golangci:
        permissions:
            contents: read
            pull-requests: read
        name: 检查代码
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: 初始化 Go
              uses: actions/setup-go@v5
              with:
                  go-version: stable
                  cache: false
            - name: 检查代码质量
              uses: golangci/golangci-lint-action@v6
              with:
                  version: latest
                  args: --verbose --timeout 30m