name: 打包并发布

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                arch:
                  - amd64
                  - "386"
        env:
            NAME: "MCSCS"
            GOOS: "windows"
            GOARCH: ${{ matrix.arch }}
        steps:
            - uses: actions/checkout@v4
            - name: 设置 Go 版本
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22.3"
            - name: 获取版本
              run: echo "VERSION=$(go run ${{ github.workspace }}/main.go --version)" >> $GITHUB_ENV
            - name: 构建
              run: go build -v -o ${{ github.workspace }}/${{ env.NAME }}.exe ${{ github.workspace }}/main.go
            - name: 测试
              run: go test -v ${{ github.workspace }}/...
            - name: 打包
              run: |
                  cd ${{ github.workspace }}
                  mv ${{ env.NAME }}.exe ${{ env.NAME }}.exe
                  zip ${{ matrix.arch }}.zip ${{ env.NAME }}.exe
            - name: 上传
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.arch }}
                  path: ${{ github.workspace }}/${{ matrix.arch }}.zip

    source:
        name: 打包源码
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: 打包
              run: |
                  cd ${{ github.workspace }}
                  tar -czvf source.tar.gz LICENSE.txt README.md --exclude=.git  --exclude=*.tar* .
                  tar -cjvf source.tar.bz2 LICENSE.txt README.md --exclude=.git  --exclude=*.tar* .
                  tar -cJvf source.tar.xz LICENSE.txt README.md --exclude=.git  --exclude=*.tar* .
            - name: 上传
              uses: actions/upload-artifact@v4
              with:
                  name: source
                  path: |
                      ${{ github.workspace }}/source.tar.gz
                      ${{ github.workspace }}/source.tar.bz2
                      ${{ github.workspace }}/source.tar.xz

    publish:
        name: 发布
        runs-on: ubuntu-latest
        needs: 
          - build
          - source
        steps:
            - name: 下载编译结果 (amd64)
              uses: actions/download-artifact@v4
              with: 
                name: amd64
                path: packages
            - name: 下载编译结果 (i386)
              uses: actions/download-artifact@v4
              with: 
                name: "386"
                path: packages
            - name: 下载打包后源码
              uses: actions/download-artifact@v4
              with: 
                name: source
                path: packages
            - name: 获取版本号
              run: echo "VERSION=$(go run ${{ github.workspace }}/main.go --version)" >> $GITHUB_ENV
            - name: 重命名
              run: |
                  cd packages
                  mv source.tar.gz MCSCS-${{ env.VERSION }}.tar.gz
                  mv source.tar.bz2 MCSCS-${{ env.VERSION }}.tar.bz2
                  mv source.tar.xz MCSCS-${{ env.VERSION }}.tar.xz
                  mv amd64.zip MCSCS-${{ env.VERSION }}-x64.zip
                  mv 386.zip MCSCS-${{ env.VERSION }}-x86.zip

            - name: 发布到 GitHub Releases
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      packages/MCSCS-${{ env.VERSION }}.tar.gz
                      packages/MCSCS-${{ env.VERSION }}.tar.bz2
                      packages/MCSCS-${{ env.VERSION }}.tar.xz
                      packages/MCSCS-${{ env.VERSION }}-x64.zip
                      packages/MCSCS-${{ env.VERSION }}-x86.zip
                  tag_name: v${{ env.VERSION }}
                  body: |
                      MCSCS-${{ env.VERSION }} 发布
                  draft: true

