name: 打包并发布

on:
    push:
        tags:
            - v*
    workflow_dispatch:
        inputs:
            version:
                description: "版本号"
                required: true

jobs:
    version:
        name: 获取版本号
        runs-on: ubuntu-latest
        outputs:
            VERSION: ${{ steps.version.outputs.VERSION }}
        steps:
            - name: 获取版本号
              id: version
              run: |
                  if [ "${{ github.event_name }}" == "push" ]; then
                    FULL_TAG="${GITHUB_REF#refs/tags/}"  
                    VERSION="${FULL_TAG#v}"
                  else
                  # 如果是手动触发，从输入参数中获取标签名称
                    VERSION="${{ github.event.inputs.version }}"
                  fi
                  echo "VERSON=$VERSION" >> $GITHUB_OUTPUT
            - name: 输出版本号
              run: "echo ${{ steps.version.outputs.VERSION }}"
    build:
        name: 编译程序
        runs-on: windows-latest
        strategy:
            matrix:
                arch:
                    - amd64
                    - "386"
        env:
            GOOS: windows
            GOARCH: ${{ matrix.arch }}
        steps:
            - uses: actions/checkout@v4
            - name: 构建
              run: go build -v -o ${{ github.workspace }}\${{ matrix.arch }}.exe ${{ github.workspace }}\cmd\MCST\main.go
            - name: 上传
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.arch }}
                  path: ${{ github.workspace }}\${{ matrix.arch }}.exe

    source:
        name: 打包源码
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: 打包
              run: |
                  cd ${{ github.workspace }}
                  tar -czvf source.tar.gz LICENSE.txt README.md --exclude=.git  --exclude=*.tar* .
                  tar -cjvf source.tar.bz2 LICENSE.txt README.md --exclude=.git  --exclude=*.tar* .
                  tar -cJvf source.tar.xz LICENSE.txt README.md --exclude=.git  --exclude=*.tar* .
            - name: 上传
              uses: actions/upload-artifact@v4
              with:
                  name: source
                  path: |
                      ${{ github.workspace }}/source.tar.gz
                      ${{ github.workspace }}/source.tar.bz2
                      ${{ github.workspace }}/source.tar.xz

    publish:
        name: 发布
        runs-on: ubuntu-latest
        needs:
            - build
            - source
            - version
        env:
            VERSION: ${{ needs.version.outputs.VERSION }}
        steps:
            - uses: actions/checkout@v4
            - name: 下载编译结果 (amd64)
              uses: actions/download-artifact@v4
              with:
                  name: amd64
                  path: packages
            - name: 下载编译结果 (i386)
              uses: actions/download-artifact@v4
              with:
                  name: "386"
                  path: packages
            - name: 下载打包后源码
              uses: actions/download-artifact@v4
              with:
                  name: source
                  path: packages
            # 忽略`Context access might be invalid: VERSION`警告, 因为这是补全未识别
            - name: 重命名并打包可执行程序
              run: |
                  cd packages
                  mv source.tar.gz MCST.tar.gz
                  mv source.tar.bz2 MCST.tar.bz2
                  mv source.tar.xz MCST.tar.xz
                  mv amd64.exe MCST.exe
                  zip MCST-x64.zip ../LICENSE.txt ../README.md MCST.exe
                  mv 386.exe MCST.exe
                  zip MCST-x86.zip ../LICENSE.txt ../README.md MCST.exe
            - name: 发布到 GitHub Releases
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      packages/MCST.tar.gz
                      packages/MCST.tar.bz2
                      packages/MCST.tar.xz
                      packages/MCST-x64.zip
                      packages/MCST-x86.zip
                  draft: true
