name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 初始化 Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: sigstore/cosign-installer@main
      - uses: anchore/sbom-action/download-syft@v0.16.0
      - name: 写入cosign私钥
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: |
          echo $COSIGN_PRIVATE_KEY > cosign.key
      - name: 创建发行版
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}