name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: anchore/sbom-action/download-syft@v0.16.0
      - uses: sigstore/cosign-installer@v3.5.0
      - run: git fetch --prune --unshallow
      - name: 写入私钥
        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > ${{ github.workspace }}/cosign.key
      - name: 创建发行版
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PWD }}